// <auto-generated />
namespace Esso.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _213213_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_213213_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201712080627523_213213_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
