// <auto-generated />
namespace Esso.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class es120220182 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(es120220182));
        
        string IMigrationMetadata.Id
        {
            get { return "201802121125561_es12022018-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
