// <auto-generated />
namespace Esso.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _6667 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_6667));
        
        string IMigrationMetadata.Id
        {
            get { return "201709181411149_6667"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
