//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esso.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_INV_OZET
    {
        [Key]
        public int Id { get; set; }
        public Nullable<DateTime> Tarih { get; set; }
        public int Inv_Id { get; set; }
        public int STATION_ID { get; set; }
        public Nullable<float> Akim_AC { get; set; }
        public Nullable<float> Akim_DC { get; set; }
        public Nullable<float> Gerilim_AC { get; set; }
        public Nullable<float> Gerilim_DC { get; set; }
        public Nullable<float> Guc_AC { get; set; }
        public Nullable<float> Guc_DC { get; set; }
        public Nullable<int> Global_State { get; set; }
        public Nullable<int> Alarm_State { get; set; }
        public Nullable<int> DC_DC_Conv_State { get; set; }
        public Nullable<int> DC_AC_Conv_State { get; set; }
        public Nullable<int> Derating_State { get; set; }
        public Nullable<float> Gunluk_Enerji { get; set; }
        public Nullable<float> Aylik_Enerji { get; set; }
        public Nullable<float> Yillik_Enerji { get; set; }
        public Nullable<float> Toplam_Enerji { get; set; }
        public Nullable<float> Isinim { get; set; }
        public Nullable<float> Ortam_Sicakligi { get; set; }
        public Nullable<float> Hucre_Sicakligi { get; set; }
        public Nullable<float> Ruzgar { get; set; }
        public Nullable<long> TARIH_NUMBER { get; set; }
        public Nullable<float> HEARTBEAT { get; set; }
        public Nullable<float> INVERTER_MAIN_STATUS { get; set; }
        public Nullable<float> REACTIVE_POWER { get; set; }
        public Nullable<float> GRID_VOLTAGE_VRMS { get; set; }
        public Nullable<float> GRID_FREQUENCY { get; set; }
        public Nullable<float> POWER_FACTOR { get; set; }
        public Nullable<float> CODE_OF_THE_ACTIVE_FAULT { get; set; }
        public Nullable<float> GRID_CURRENT { get; set; }
        public Nullable<float> DC_BUS_VOLTAGE { get; set; }
        public Nullable<float> GROUNDING_CURRENT { get; set; }
        public Nullable<float> SOLATION_RESISTANCE { get; set; }
        public Nullable<float> AMBIENT_TEMPERATURE { get; set; }
        public Nullable<float> HIGHEST_IGBT_TEMPERATURE_PU1 { get; set; }
        public Nullable<float> HIGHEST_IGBT_TEMPERATURE_PU2 { get; set; }
        public Nullable<float> HIGHEST_IGBT_TEMPERATURE_PU3 { get; set; }
        public Nullable<float> HIGHEST_IGBT_TEMPERATURE_PU4 { get; set; }
        public Nullable<float> CONTROL_SECTION_TEMPERATURE { get; set; }
        public Nullable<float> DAILY_KVAH_SUPPLIED { get; set; }
        public Nullable<float> TOTAL_KVAH_SUPPLIED { get; set; }
        public Nullable<float> IGBT_1_T1 { get; set; }
        public Nullable<float> IGBT_1_T2 { get; set; }
        public Nullable<float> IGBT_1_T3 { get; set; }
        public Nullable<float> IGBT_2_T1 { get; set; }
        public Nullable<float> IGBT_2_T2 { get; set; }
        public Nullable<float> IGBT_2_T3 { get; set; }
        public Nullable<float> IGBT_3_T1 { get; set; }
        public Nullable<float> IGBT_3_T2 { get; set; }
        public Nullable<float> IGBT_3_T3 { get; set; }
        public Nullable<float> IGBT_4_T1 { get; set; }
        public Nullable<float> IGBT_4_T2 { get; set; }
        public Nullable<float> IGBT_4_T3 { get; set; }
    }
}
